
server:
   port: 8082
greeting:
   message: Say Hello to the World

---
server:
  port: 8082

spring:

     main:
        allow-bean-definition-overriding: true
#
     datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.30:3306/tx?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      servlet:
       multipart:
       max-file-size: 20MB
       max-request-size: 20MB
        # REDIS
       # Redis数据库索引（默认为0）

      # 使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      filters: stat, wall
      initialSize: 5
    # 最大和最小连接池数量
      maxActive: 20
      minIdle: 5
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validationQuery: SELECT 1 FROM DUAL
     #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
    #通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall

    # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true


      redis:
       database: 0
       # Redis服务器地址 （默认为127.0.0.1）
       host: 127.0.0.1
       # Redis服务器连接端口 （默认为6379）
       port: 6379
       # Redis服务器连接密码（默认为空）
       password:
       # 连接超时时间（毫秒）
       timeout: 2000


mybatis:
     mapper-locations: classpath:mapper/*.xml
     type-aliases-package: com.tx.out.bean
